language: ruby

rvm:
  - 2.0.0
bundler_args: --without development production

# This essentially defines a build pipeline: we first run the full set of locally runnable tests (unit + functional)
# For master pushes, we then deploy to the test site and push on to the staging branch.
# Travis then builds the staging branch, which runs integration tests against the newly-live staging deployment
# Once these pass, Travis deploys the code to live, and pushes to the prod branch (mostly just for reference)

# These also a special case for pull requests: these never push or deploy, and run the whole local test suite only

script:
  - if [[ "$TRAVIS_BRANCH" != "staging" ]]; then rake local_test; fi
  - if [[ "$TRAVIS_BRANCH" == "staging" ]]; then rake staging_integration; fi

deploy:
  provider: heroku
  app:
    master: tim-perry-test
    staging: tim-perry
  api_key:
    secure: jbSFy9O9KS08AZK1LVpYF7ZDX2eU0hoqh3wcsBulm2Dydp0i03p7cJgi+ZIn0wE8hmZ0L9DLBL13v6+6qylan0YtUTjWDEaNRTkE4WR145QtTIu8dSUPsc9/6O6yD7IMqjqoP7SGXX0PC/jKaJZykV8sWgawUx9gakYIIQi+43c=

after_success:
  # Various pushes to branches. Need to pipe to null to not expose OAuth token
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      git push https://${GH_OAUTH_TOKEN}@github.com/pimterry/tim-perry.co.uk master:staging > /dev/null 2>&1;
    fi
  - if [[ "$TRAVIS_BRANCH" == "staging" ]]; then
      git push https://${GH_OAUTH_TOKEN}@github.com/pimterry/tim-perry.co.uk staging:prod > /dev/null 2>&1;
    fi

branches:
  except:
    - prod # No point in building prod, since we've just pushed from successful staging & master builds already

env:
  global:
    secure: glmgbyVmjjUnP1jjlAwFjLSlY0mz0B1o8AeLzVhPK+sdPSW0L7qY6lyQwVVS4wpCPCiTmIw5qWLRiyhtaHLOU0r9E9/fZ30Gonfg/HJMlcmRfcjiabwqdtDBg2m1Pnpl9+l2tPsCwye7A67iORMvGlZqVgfnKGeINk5/uA6WEXU=